### ISSUE TITLE
File is downloaded before it's determined that it already exists

### ISSUE THREAD

**Issue by morrisonbrett** [morrisonbrett/BlackVueDownloader#17]
It should not download it if it already exists.

Reported by: Ken Page

**Comment by vk4akp** [comment]
Hi, Just wondered how you were going with this? I've had a couple of incidents now where I've needed footage but due to the restart issue the recordings have rolled over the top of what I needed as the camera still records in "Park Mode" while the download script downloads the same files over and over then says already exists. By the time I get back to where it left off it's been recorded over the top with new footage :( .-.-.

**Comment by morrisonbrett** [comment]
This is now fixed. @vk4akp please download the latest release.
